### PR TITLE
WIP: Install aragon vault app into Kredits kit

### PR DESCRIPTION
**Pull request by haythem96**
for Kredits DAO to accept funds (ETH or ERC20 token) it need a vault app to manage(receive & hold) those funds. And aragon apps packages have a Vault app that do the same functionalities that we need, so in this code it just import that app from the @aragon/vault-app package and install it into Kredits kit.

Vault app doc: https://wiki.aragon.org/dev/apps/vault/

Related to #169

### CODE REVIEW

**Comment by bumi** [comment]
This looks actually pretty cool. :+1: 
The main question will be who will have the transfer role. To test we could add a CLI script to transfer from the vault. 
Also we should add a JS wrapper class for the vault to be able to easily interact with it from JS.

**Comment by haythem96** [comment]
> This looks actually pretty cool. 
> The main question will be who will have the transfer role. To test we could add a CLI script to transfer from the vault.
> Also we should add a JS wrapper class for the vault to be able to easily interact with it from JS.

For the transfer role, I think the Reward app (when it is ready) should have it

**Comment by skddc** [comment]
Could you explain a bit what this does and how it works? The PR description is basically empty.

**Comment by haythem96** [comment]
> Could you explain a bit what this does and how it works? The PR description is basically empty. Thanks!

Yeah sorry about that... need to better write PR description

So basically for Kredits DAO to accept funds (ether or erc20 token) it need a vault app to manage(receive & hold) those funds. And aragon apps packages have a `Vault` app that do the same functionalities that we need, so in this code it just import that app from the `@aragon/vault-app` package and install it into Kredits kit.

**Comment by skddc** [comment]
Maybe you could link to documentation of the Vault app?

**Comment by raucao** [comment]
Closing due to inactivity. Please feel free to re-open.

**Comment by raucao** [comment]
Closing due to inactivity. Please feel free to re-open.

**Pull request closed without merging**
