### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by bumi**

### CODE REVIEW

**Comment by skddc** [comment]
There's an issue with Travis (not due to this change), and I'm not sure why it's using Yarn in the first place.

**Comment by bumi** [comment]
hmmm... and what is `del-cli` https://www.npmjs.com/package/del-cli ?!

**Comment by bumi** [comment]
seems it is caused by some postinstall script of a package: https://github.com/aragon/aragon-cli/blob/master/packages/aragon-cli/package.json#L11-L12 (actually scary that it does something like 'del-cli' on postinstall)

**Comment by bumi** [comment]
using npm install it seems to work. @fsmanuel do you maybe have an idea what could be the issue here?

**Comment by skddc** [comment]
Yay!

**Pull request merged**
