### PR TITLE
Add linter and travis.yml

### PR DESCRIPTION
**Pull request by fsmanuel**
Let's discuss the linting rules!
I adopted Bastis use of a space between the function name and the parentheses: 
`serialize () {`
and added a `comma-dangle` rule.

I have no idea on the solidity rules. Right now it complains about spaces...
https://github.com/protofire/solhint
https://github.com/protofire/solhint/blob/master/docs/rules.md

### CODE REVIEW

**Comment by fsmanuel** [comment]
I decided to use the `solhint:recommended` ruleset.

**Comment by bumi** [comment]
yay! :+1: 

I will look at that solidity code and try to update it. - no idea about the rules there.

**Comment by fsmanuel** [comment]
I like the dangling comma because of the cleaner diff.

Here are the JS errors:

```
/home/travis/build/67P/kredits-contracts/lib/kredits.js
  54:11  error  Unexpected console statement  no-console
  65:5   error  Unexpected console statement  no-console
  83:5   error  Unexpected console statement  no-console

/home/travis/build/67P/kredits-contracts/lib/utils/validator.js
  10:94  error  Unnecessary escape character: \+  no-useless-escape
  10:97  error  Unnecessary escape character: \-  no-useless-escape
```

What should we do about the `no-console` rules? Should we allow it globally or add a `log()` utils function and allow it there?

**Comment by fsmanuel** [comment]
I found another linter https://github.com/duaraghav8/Ethlint it is used by aragon-apps so maybe we should consider to use it as well...

**Comment by bumi** [comment]
I did not have the time to look at the solidity stuff and also probably won't in the next days. 
maybe we merge this without the solidity part?

**Comment by fsmanuel** [comment]
@bumi I disabled the solidity checks for now. Would be great to merge as is and pickup on solidity later.

**Comment by fsmanuel** [comment]
Someone needs to update the `package-lock.json` as it doesn't work for me.

**Comment by fsmanuel** [comment]
@bumi ❤️

**Comment by bumi** [comment]
but this looks more like a `kredits-2` ?

**Comment by fsmanuel** [comment]
So change and merge it!

**Pull request merged**
