### PR TITLE
Remove Aragon CLI, document system deps

### PR DESCRIPTION
**Pull request by skddc**
In order to prevent regular issues with the notoriously npm-issue-ridden Aragon CLI module, this removes it as a direct dependency and requires it to be installed as a system dependency.

Also adds Truffle as a system dependency to the docs (which was missing before).

The latest Aragon CLI asks has a lot of prompts for every contract deployment. I'll see if we can remove those by specifying more arguments upfront.

refs #158

### CODE REVIEW

**Comment by bumi** [comment]
this is awesome! thanks for looking into it. 
maybe we can add the used/tested aragon and truffle version to the readme? 

and I think that's a `kredits-2`

**Comment by skddc** [comment]
>  maybe we can add the used/tested aragon and truffle version to the readme?

Then we have to update it like every two days. They release *a lot* over at Aragon. :)


> and I think that's a `kredits-2`

Nah, 1 is perfectly fine. Didn't take long.

**Comment by skddc** [comment]
Tests are also green after adding sys deps. Merging...

**Comment by bumi** [comment]
> Then we have to update it like every two days. They release _a lot_ over at Aragon. :)

yep, but also breaking changes. - at least we have to keep in mind which versions we are using/supporting

**Comment by skddc** [comment]
Whoever sees something breaking with the latest version on their system should open an issue imo.

**Pull request merged**
