### PR TITLE
Update to ethers 5

### PR DESCRIPTION
**Pull request by bumi**

### CODE REVIEW

**Comment by skddc** [comment]
Sure that's a kredits-1 and not a 2?

**Comment by bumi** [comment]
yeah no idea. was quite some trouble and work, but in the end it's not that much...

**Comment by skddc** [comment]
Bootstrap and scripts work for me. But the hubot-kredits PR does not. See comment on 67P/hubot-kredits#59.

**Comment by bumi** [comment]
merging this and preparing a new release.

**Pull request merged**
