### PR TITLE
Fix util import

### PR DESCRIPTION
**Pull request by bumi**

### CODE REVIEW

**Comment by bumi** [comment]
merging as it is currently broken. but this should be a `kredits-0` maybe?

**Comment by skddc** [comment]
> but this should be a `kredits-0` maybe?

You did fix it, and you'll have to publish the npm module, too. So I don't see how it's not a valuable small contribution.

**Comment by bumi** [comment]
it was only broken in master, the latest release is still fine as far as I checked.

**Comment by skddc** [comment]
Well, then a core team member you can still merge without the label, if you want.

**Pull request merged**
