### PR TITLE
Update aragon CLI to latest version

### PR DESCRIPTION
**Pull request by bumi**
updated aragon-cli everywhere and ran a fresh npm install everywhere. 
(removed node_modules and package-lock.json before installing)

### CODE REVIEW

**Comment by skddc** [comment]
Unfortunately, the build is still red. :/

**Comment by skddc** [comment]
Update: I get exactly the same error when `npm install`ing from this branch with empty `node_modules`.

**Comment by skddc** [comment]
There seems to be some kind of chicken-and-egg problem. It only works when deleting the package lockfile beforehand. But a bootstrapped install then takes forever, due to the gazillion deps including native extensions.

**Comment by bumi** [comment]
It seems to me that a `postinstall` script defined in the package.json of the aragon-cli is doing something: https://github.com/aragon/aragon-cli/blob/master/packages/aragon-cli/scripts/fix-lockfile

fund also this related: 
https://github.com/aragon/aragon-cli/blob/master/docs-internal/Dependencies.md#regenerate-the-lockfiles

**Comment by bumi** [comment]
closing in favor of #140 and #142

**Pull request closed without merging**
